using System;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace Mta.Api.Migrations
{
    /// <inheritdoc />
    public partial class CmsFaqs : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.CreateTable(
                name: "Faqs",
                columns: table => new
                {
                    Id = table.Column<Guid>(type: "uuid", nullable: false),
                    Scope = table.Column<string>(type: "text", nullable: false),
                    CategoryKa = table.Column<string>(type: "text", nullable: false),
                    CategoryEn = table.Column<string>(type: "text", nullable: false),
                    QuestionKa = table.Column<string>(type: "text", nullable: false),
                    AnswerKa = table.Column<string>(type: "text", nullable: false),
                    QuestionEn = table.Column<string>(type: "text", nullable: false),
                    AnswerEn = table.Column<string>(type: "text", nullable: false),
                    SortOrder = table.Column<int>(type: "integer", nullable: false),
                    Published = table.Column<bool>(type: "boolean", nullable: false),
                    Version = table.Column<Guid>(type: "uuid", nullable: false),
                    UpdatedAt = table.Column<DateTimeOffset>(type: "timestamp with time zone", nullable: false)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_Faqs", x => x.Id);
                });

            migrationBuilder.CreateIndex(
                name: "IX_Faqs_Scope_Published_SortOrder",
                table: "Faqs",
                columns: new[] { "Scope", "Published", "SortOrder" });
            // One-time copy of the former bilingual frontend FAQ content.
            migrationBuilder.InsertData("Faqs", new[] { "Id", "Scope", "CategoryKa", "CategoryEn", "QuestionKa", "AnswerKa", "QuestionEn", "AnswerEn", "SortOrder", "Published", "Version", "UpdatedAt" }, new object[] { new Guid("fa000000-0000-4000-8000-000000000001"), "", "სკიპასი", "Ski Pass", "როგორ შევიძინო სკიპასი?", "სკიპასის შეძენა შესაძლებელია სააგენტოს გაყიდვის ხელმისაწვდომი არხებით. მიმდინარე შეთავაზებების სანახავად ეწვიეთ დაგეგმვისა და დაჯავშნის განყოფილებას.", "How can I buy a ski pass?", "Ski passes can be purchased through the available Mountain Resorts Agency sales channels. Check the Plan & Book section for current purchasing options.", 0, true, new Guid("fb000000-0000-4000-8000-000000000001"), new DateTimeOffset(2026, 9, 25, 0, 0, 0, TimeSpan.Zero) });
            migrationBuilder.InsertData("Faqs", new[] { "Id", "Scope", "CategoryKa", "CategoryEn", "QuestionKa", "AnswerKa", "QuestionEn", "AnswerEn", "SortOrder", "Published", "Version", "UpdatedAt" }, new object[] { new Guid("fa000000-0000-4000-8000-000000000002"), "", "სკიპასი", "Ski Pass", "შემიძლია სკიპასის შევსება?", "დიახ. სკიპასის შევსება შესაძლებელია შესაბამისი მომსახურების საშუალებით.", "Can I recharge my ski pass?", "Yes. Recharge options are available through the available ski pass services.", 10, true, new Guid("fb000000-0000-4000-8000-000000000002"), new DateTimeOffset(2026, 9, 25, 0, 0, 0, TimeSpan.Zero) });
            migrationBuilder.InsertData("Faqs", new[] { "Id", "Scope", "CategoryKa", "CategoryEn", "QuestionKa", "AnswerKa", "QuestionEn", "AnswerEn", "SortOrder", "Published", "Version", "UpdatedAt" }, new object[] { new Guid("fa000000-0000-4000-8000-000000000003"), "", "სკიპასი", "Ski Pass", "შემიძლია სკიპასის თანხის დაბრუნება?", "თანხის დაბრუნების პირობები დამოკიდებულია სკიპასის ტიპსა და მოქმედ წესებზე.", "Can I get a refund for my ski pass?", "Refund conditions depend on the type of ski pass and the applicable terms.", 20, true, new Guid("fb000000-0000-4000-8000-000000000003"), new DateTimeOffset(2026, 9, 25, 0, 0, 0, TimeSpan.Zero) });
            migrationBuilder.InsertData("Faqs", new[] { "Id", "Scope", "CategoryKa", "CategoryEn", "QuestionKa", "AnswerKa", "QuestionEn", "AnswerEn", "SortOrder", "Published", "Version", "UpdatedAt" }, new object[] { new Guid("fa000000-0000-4000-8000-000000000004"), "", "სკიპასი", "Ski Pass", "შემიძლია ერთი სკიპასით სხვადასხვა კურორტზე სარგებლობა?", "ეს დამოკიდებულია შეძენილი სკიპასის ტიპზე. შეამოწმეთ თქვენი სკიპასის პირობები.", "Can I use one ski pass at different resorts?", "This depends on the type of ski pass you have purchased. Please check the conditions of your specific pass.", 30, true, new Guid("fb000000-0000-4000-8000-000000000004"), new DateTimeOffset(2026, 9, 25, 0, 0, 0, TimeSpan.Zero) });
            migrationBuilder.InsertData("Faqs", new[] { "Id", "Scope", "CategoryKa", "CategoryEn", "QuestionKa", "AnswerKa", "QuestionEn", "AnswerEn", "SortOrder", "Published", "Version", "UpdatedAt" }, new object[] { new Guid("fa000000-0000-4000-8000-000000000005"), "", "საბაგიროები და ტრასები", "Lifts & Slopes", "როგორ გავიგო, რომელი საბაგირო მუშაობს?", "საბაგიროებისა და ტრასების მიმდინარე მდგომარეობა შეგიძლიათ შეამოწმოთ მიმდინარე სტატუსის განყოფილებაში.", "How can I check which lifts are open?", "You can check the current operating status of lifts and slopes through the Live Status section.", 40, true, new Guid("fb000000-0000-4000-8000-000000000005"), new DateTimeOffset(2026, 9, 25, 0, 0, 0, TimeSpan.Zero) });
            migrationBuilder.InsertData("Faqs", new[] { "Id", "Scope", "CategoryKa", "CategoryEn", "QuestionKa", "AnswerKa", "QuestionEn", "AnswerEn", "SortOrder", "Published", "Version", "UpdatedAt" }, new object[] { new Guid("fa000000-0000-4000-8000-000000000006"), "", "საბაგიროები და ტრასები", "Lifts & Slopes", "სად ვიპოვო ინფორმაცია სათხილამურო ტრასებზე?", "ტრასების, სირთულის დონეებისა და ინფრასტრუქტურის შესახებ დეტალები მოცემულია კურორტების გვერდებსა და რუკებზე.", "Where can I find information about ski slopes?", "Detailed information about slopes, difficulty levels and resort infrastructure can be found on the resort pages and maps.", 50, true, new Guid("fb000000-0000-4000-8000-000000000006"), new DateTimeOffset(2026, 9, 25, 0, 0, 0, TimeSpan.Zero) });
            migrationBuilder.InsertData("Faqs", new[] { "Id", "Scope", "CategoryKa", "CategoryEn", "QuestionKa", "AnswerKa", "QuestionEn", "AnswerEn", "SortOrder", "Published", "Version", "UpdatedAt" }, new object[] { new Guid("fa000000-0000-4000-8000-000000000007"), "", "საბაგიროები და ტრასები", "Lifts & Slopes", "რა ხდება საბაგიროს დროებით დახურვისას?", "საბაგიროს მუშაობა დამოკიდებულია ამინდზე, ტექნიკურ მდგომარეობასა და უსაფრთხოებაზე. გამგზავრებამდე ყოველთვის შეამოწმეთ მიმდინარე სტატუსი.", "What happens if a lift is temporarily closed?", "Lift operations can be affected by weather, technical conditions or safety requirements. Always check the current Live Status before heading to the slopes.", 60, true, new Guid("fb000000-0000-4000-8000-000000000007"), new DateTimeOffset(2026, 9, 25, 0, 0, 0, TimeSpan.Zero) });
            migrationBuilder.InsertData("Faqs", new[] { "Id", "Scope", "CategoryKa", "CategoryEn", "QuestionKa", "AnswerKa", "QuestionEn", "AnswerEn", "SortOrder", "Published", "Version", "UpdatedAt" }, new object[] { new Guid("fa000000-0000-4000-8000-000000000008"), "", "საბაგიროები და ტრასები", "Lifts & Slopes", "სად ვიპოვო კურორტების რუკები?", "კურორტების რუკები ხელმისაწვდომია რუკების განყოფილებასა და შესაბამისი კურორტის გვერდზე.", "Where can I find resort maps?", "Resort maps are available through the Maps section and on the relevant resort information pages.", 70, true, new Guid("fb000000-0000-4000-8000-000000000008"), new DateTimeOffset(2026, 9, 25, 0, 0, 0, TimeSpan.Zero) });
            migrationBuilder.InsertData("Faqs", new[] { "Id", "Scope", "CategoryKa", "CategoryEn", "QuestionKa", "AnswerKa", "QuestionEn", "AnswerEn", "SortOrder", "Published", "Version", "UpdatedAt" }, new object[] { new Guid("fa000000-0000-4000-8000-000000000009"), "", "ბავშვები და სტუდენტები", "Children & Students", "არის ბავშვებისთვის სკიპასის სპეციალური პირობები?", "ბავშვებისთვის შესაძლოა ასაკობრივი პირობები მოქმედებდეს. გაეცანით სკიპასის უახლეს ინფორმაციას ასაკობრივი კატეგორიებისა და მოთხოვნების შესახებ.", "Are there special ski pass conditions for children?", "Special age-based conditions may apply to children. Check the latest ski pass information for current age categories and requirements.", 80, true, new Guid("fb000000-0000-4000-8000-000000000009"), new DateTimeOffset(2026, 9, 25, 0, 0, 0, TimeSpan.Zero) });
            migrationBuilder.InsertData("Faqs", new[] { "Id", "Scope", "CategoryKa", "CategoryEn", "QuestionKa", "AnswerKa", "QuestionEn", "AnswerEn", "SortOrder", "Published", "Version", "UpdatedAt" }, new object[] { new Guid("fa000000-0000-4000-8000-000000000010"), "", "ბავშვები და სტუდენტები", "Children & Students", "არის სტუდენტური ფასდაკლება?", "სტუდენტური პირობები და ფასდაკლებები დამოკიდებულია სკიპასის მოქმედ პოლიტიკაზე.", "Are there discounts for students?", "Student conditions and discounts may vary depending on the current ski pass policy.", 90, true, new Guid("fb000000-0000-4000-8000-000000000010"), new DateTimeOffset(2026, 9, 25, 0, 0, 0, TimeSpan.Zero) });
            migrationBuilder.InsertData("Faqs", new[] { "Id", "Scope", "CategoryKa", "CategoryEn", "QuestionKa", "AnswerKa", "QuestionEn", "AnswerEn", "SortOrder", "Published", "Version", "UpdatedAt" }, new object[] { new Guid("fa000000-0000-4000-8000-000000000011"), "", "ბავშვები და სტუდენტები", "Children & Students", "სჭირდებათ ბავშვებს საკუთარი სკიპასი?", "მოთხოვნები დამოკიდებულია ბავშვის ასაკსა და კურორტის მოქმედ წესებზე.", "Do children need their own ski pass?", "Requirements depend on the child's age and the applicable resort rules.", 100, true, new Guid("fb000000-0000-4000-8000-000000000011"), new DateTimeOffset(2026, 9, 25, 0, 0, 0, TimeSpan.Zero) });
            migrationBuilder.InsertData("Faqs", new[] { "Id", "Scope", "CategoryKa", "CategoryEn", "QuestionKa", "AnswerKa", "QuestionEn", "AnswerEn", "SortOrder", "Published", "Version", "UpdatedAt" }, new object[] { new Guid("fa000000-0000-4000-8000-000000000012"), "", "კურორტები", "Resorts", "რომელი სათხილამურო კურორტების მონახულება შემიძლია?", "კურორტების განყოფილებაში გაეცანით მთის მიმართულებებსა და მათ შესაძლებლობებს.", "Which ski resorts can I visit?", "Explore the Resorts section to discover available mountain destinations and their facilities.", 110, true, new Guid("fb000000-0000-4000-8000-000000000012"), new DateTimeOffset(2026, 9, 25, 0, 0, 0, TimeSpan.Zero) });
            migrationBuilder.InsertData("Faqs", new[] { "Id", "Scope", "CategoryKa", "CategoryEn", "QuestionKa", "AnswerKa", "QuestionEn", "AnswerEn", "SortOrder", "Published", "Version", "UpdatedAt" }, new object[] { new Guid("fa000000-0000-4000-8000-000000000013"), "", "კურორტები", "Resorts", "სად ვნახო კურორტის სამუშაო საათები?", "სამუშაო საათები მოცემულია კურორტის გვერდზე და შეიძლება შეიცვალოს ამინდისა და ოპერაციული პირობების მიხედვით.", "Where can I find resort opening hours?", "Current operating hours are displayed on the relevant resort pages and may change depending on weather and operational conditions.", 120, true, new Guid("fb000000-0000-4000-8000-000000000013"), new DateTimeOffset(2026, 9, 25, 0, 0, 0, TimeSpan.Zero) });
            migrationBuilder.InsertData("Faqs", new[] { "Id", "Scope", "CategoryKa", "CategoryEn", "QuestionKa", "AnswerKa", "QuestionEn", "AnswerEn", "SortOrder", "Published", "Version", "UpdatedAt" }, new object[] { new Guid("fa000000-0000-4000-8000-000000000014"), "", "კურორტები", "Resorts", "სად ვიპოვო ინფორმაცია განთავსებისა და აქტივობების შესახებ?", "კურორტის გვერდზე გაეცანით აქტივობებს, ახლომდებარე მომსახურებასა და ღირსშესანიშნაობებს.", "Where can I find accommodation and activities?", "Explore each resort page for information about activities, nearby services and attractions.", 130, true, new Guid("fb000000-0000-4000-8000-000000000014"), new DateTimeOffset(2026, 9, 25, 0, 0, 0, TimeSpan.Zero) });
            migrationBuilder.InsertData("Faqs", new[] { "Id", "Scope", "CategoryKa", "CategoryEn", "QuestionKa", "AnswerKa", "QuestionEn", "AnswerEn", "SortOrder", "Published", "Version", "UpdatedAt" }, new object[] { new Guid("fa000000-0000-4000-8000-000000000015"), "gudauri-kobi", "", "", "როდის არის სტუმრობის საუკეთესო დრო?", "ზამთრისა და ზაფხულის პირობები კურორტების მიხედვით განსხვავდება. გამგზავრებამდე შეამოწმეთ ოფიციალური მიმდინარე სტატუსი.", "When is the best time to visit?", "Winter conditions and the summer mountain season differ by resort. Check the official live-status service before you travel.", 0, true, new Guid("fb000000-0000-4000-8000-000000000015"), new DateTimeOffset(2026, 9, 25, 0, 0, 0, TimeSpan.Zero) });
            migrationBuilder.InsertData("Faqs", new[] { "Id", "Scope", "CategoryKa", "CategoryEn", "QuestionKa", "AnswerKa", "QuestionEn", "AnswerEn", "SortOrder", "Published", "Version", "UpdatedAt" }, new object[] { new Guid("fa000000-0000-4000-8000-000000000016"), "gudauri-kobi", "", "", "შეუძლიათ აქ დამწყებებს სრიალი?", "გუდაური და კობი სხვადასხვა დონის მოთხილამურეებისთვისაა განკუთვნილი. დამწყებებმა შესაბამისი ზონები უნდა აირჩიონ და გაითვალისწინონ ინსტრუქტორის ან გიდის დახმარება.", "Can beginners ski here?", "Gudauri & Kobi offers terrain for a range of abilities. Beginners should choose suitable areas and consider a lesson or local guide.", 10, true, new Guid("fb000000-0000-4000-8000-000000000016"), new DateTimeOffset(2026, 9, 25, 0, 0, 0, TimeSpan.Zero) });
            migrationBuilder.InsertData("Faqs", new[] { "Id", "Scope", "CategoryKa", "CategoryEn", "QuestionKa", "AnswerKa", "QuestionEn", "AnswerEn", "SortOrder", "Published", "Version", "UpdatedAt" }, new object[] { new Guid("fa000000-0000-4000-8000-000000000017"), "gudauri-kobi", "", "", "შემიძლია სტუმრობა სრიალის გარეშე?", "დიახ. პანორამული საბაგიროები, კვება, მთის ხედები და სეზონური აქტივობები სრიალის გარეშეც სასიამოვნო დასვენებას გთავაზობთ.", "Can I visit without skiing?", "Yes. Scenic lifts, food, mountain views and seasonal outdoor activities make the resort enjoyable beyond skiing.", 20, true, new Guid("fb000000-0000-4000-8000-000000000017"), new DateTimeOffset(2026, 9, 25, 0, 0, 0, TimeSpan.Zero) });
            migrationBuilder.InsertData("Faqs", new[] { "Id", "Scope", "CategoryKa", "CategoryEn", "QuestionKa", "AnswerKa", "QuestionEn", "AnswerEn", "SortOrder", "Published", "Version", "UpdatedAt" }, new object[] { new Guid("fa000000-0000-4000-8000-000000000018"), "gudauri-kobi", "", "", "შემიძლია სკიპასის ონლაინ შეძენა?", "სკიპასის ხელმისაწვდომობის, ფასებისა და შეძენის გზების გასაგებად გამოიყენეთ სააგენტოს ოფიციალური არხები.", "Can I buy a ski pass online?", "Please use official MTA channels for current ski-pass availability, prices and purchase options.", 30, true, new Guid("fb000000-0000-4000-8000-000000000018"), new DateTimeOffset(2026, 9, 25, 0, 0, 0, TimeSpan.Zero) });
            migrationBuilder.InsertData("Faqs", new[] { "Id", "Scope", "CategoryKa", "CategoryEn", "QuestionKa", "AnswerKa", "QuestionEn", "AnswerEn", "SortOrder", "Published", "Version", "UpdatedAt" }, new object[] { new Guid("fa000000-0000-4000-8000-000000000019"), "gudauri-kobi", "", "", "მუშაობს კურორტები ზაფხულში?", "ზაფხულის შეთავაზებები და სამუშაო საათები განსხვავდება. უახლესი ინფორმაციისთვის შეამოწმეთ ოფიციალური მიმდინარე სტატუსი.", "Are the resorts open during summer?", "Summer offerings and operating hours vary. Check the official live-status service for the latest information.", 40, true, new Guid("fb000000-0000-4000-8000-000000000019"), new DateTimeOffset(2026, 9, 25, 0, 0, 0, TimeSpan.Zero) });
            migrationBuilder.InsertData("Faqs", new[] { "Id", "Scope", "CategoryKa", "CategoryEn", "QuestionKa", "AnswerKa", "QuestionEn", "AnswerEn", "SortOrder", "Published", "Version", "UpdatedAt" }, new object[] { new Guid("fa000000-0000-4000-8000-000000000020"), "bakuriani", "", "", "როდის არის სტუმრობის საუკეთესო დრო?", "ზამთრისა და ზაფხულის პირობები კურორტების მიხედვით განსხვავდება. გამგზავრებამდე შეამოწმეთ ოფიციალური მიმდინარე სტატუსი.", "When is the best time to visit?", "Winter conditions and the summer mountain season differ by resort. Check the official live-status service before you travel.", 0, true, new Guid("fb000000-0000-4000-8000-000000000020"), new DateTimeOffset(2026, 9, 25, 0, 0, 0, TimeSpan.Zero) });
            migrationBuilder.InsertData("Faqs", new[] { "Id", "Scope", "CategoryKa", "CategoryEn", "QuestionKa", "AnswerKa", "QuestionEn", "AnswerEn", "SortOrder", "Published", "Version", "UpdatedAt" }, new object[] { new Guid("fa000000-0000-4000-8000-000000000021"), "bakuriani", "", "", "შეუძლიათ აქ დამწყებებს სრიალი?", "ბაკურიანი სხვადასხვა დონის მოთხილამურეებისთვისაა განკუთვნილი. დამწყებებმა შესაბამისი ზონები უნდა აირჩიონ და გაითვალისწინონ ინსტრუქტორის ან გიდის დახმარება.", "Can beginners ski here?", "Bakuriani offers terrain for a range of abilities. Beginners should choose suitable areas and consider a lesson or local guide.", 10, true, new Guid("fb000000-0000-4000-8000-000000000021"), new DateTimeOffset(2026, 9, 25, 0, 0, 0, TimeSpan.Zero) });
            migrationBuilder.InsertData("Faqs", new[] { "Id", "Scope", "CategoryKa", "CategoryEn", "QuestionKa", "AnswerKa", "QuestionEn", "AnswerEn", "SortOrder", "Published", "Version", "UpdatedAt" }, new object[] { new Guid("fa000000-0000-4000-8000-000000000022"), "bakuriani", "", "", "შემიძლია სტუმრობა სრიალის გარეშე?", "დიახ. პანორამული საბაგიროები, კვება, მთის ხედები და სეზონური აქტივობები სრიალის გარეშეც სასიამოვნო დასვენებას გთავაზობთ.", "Can I visit without skiing?", "Yes. Scenic lifts, food, mountain views and seasonal outdoor activities make the resort enjoyable beyond skiing.", 20, true, new Guid("fb000000-0000-4000-8000-000000000022"), new DateTimeOffset(2026, 9, 25, 0, 0, 0, TimeSpan.Zero) });
            migrationBuilder.InsertData("Faqs", new[] { "Id", "Scope", "CategoryKa", "CategoryEn", "QuestionKa", "AnswerKa", "QuestionEn", "AnswerEn", "SortOrder", "Published", "Version", "UpdatedAt" }, new object[] { new Guid("fa000000-0000-4000-8000-000000000023"), "bakuriani", "", "", "შემიძლია სკიპასის ონლაინ შეძენა?", "სკიპასის ხელმისაწვდომობის, ფასებისა და შეძენის გზების გასაგებად გამოიყენეთ სააგენტოს ოფიციალური არხები.", "Can I buy a ski pass online?", "Please use official MTA channels for current ski-pass availability, prices and purchase options.", 30, true, new Guid("fb000000-0000-4000-8000-000000000023"), new DateTimeOffset(2026, 9, 25, 0, 0, 0, TimeSpan.Zero) });
            migrationBuilder.InsertData("Faqs", new[] { "Id", "Scope", "CategoryKa", "CategoryEn", "QuestionKa", "AnswerKa", "QuestionEn", "AnswerEn", "SortOrder", "Published", "Version", "UpdatedAt" }, new object[] { new Guid("fa000000-0000-4000-8000-000000000024"), "bakuriani", "", "", "მუშაობს კურორტები ზაფხულში?", "ზაფხულის შეთავაზებები და სამუშაო საათები განსხვავდება. უახლესი ინფორმაციისთვის შეამოწმეთ ოფიციალური მიმდინარე სტატუსი.", "Are the resorts open during summer?", "Summer offerings and operating hours vary. Check the official live-status service for the latest information.", 40, true, new Guid("fb000000-0000-4000-8000-000000000024"), new DateTimeOffset(2026, 9, 25, 0, 0, 0, TimeSpan.Zero) });
            migrationBuilder.InsertData("Faqs", new[] { "Id", "Scope", "CategoryKa", "CategoryEn", "QuestionKa", "AnswerKa", "QuestionEn", "AnswerEn", "SortOrder", "Published", "Version", "UpdatedAt" }, new object[] { new Guid("fa000000-0000-4000-8000-000000000025"), "mestia", "", "", "როდის არის სტუმრობის საუკეთესო დრო?", "ზამთრისა და ზაფხულის პირობები კურორტების მიხედვით განსხვავდება. გამგზავრებამდე შეამოწმეთ ოფიციალური მიმდინარე სტატუსი.", "When is the best time to visit?", "Winter conditions and the summer mountain season differ by resort. Check the official live-status service before you travel.", 0, true, new Guid("fb000000-0000-4000-8000-000000000025"), new DateTimeOffset(2026, 9, 25, 0, 0, 0, TimeSpan.Zero) });
            migrationBuilder.InsertData("Faqs", new[] { "Id", "Scope", "CategoryKa", "CategoryEn", "QuestionKa", "AnswerKa", "QuestionEn", "AnswerEn", "SortOrder", "Published", "Version", "UpdatedAt" }, new object[] { new Guid("fa000000-0000-4000-8000-000000000026"), "mestia", "", "", "შეუძლიათ აქ დამწყებებს სრიალი?", "მესტია სხვადასხვა დონის მოთხილამურეებისთვისაა განკუთვნილი. დამწყებებმა შესაბამისი ზონები უნდა აირჩიონ და გაითვალისწინონ ინსტრუქტორის ან გიდის დახმარება.", "Can beginners ski here?", "Mestia offers terrain for a range of abilities. Beginners should choose suitable areas and consider a lesson or local guide.", 10, true, new Guid("fb000000-0000-4000-8000-000000000026"), new DateTimeOffset(2026, 9, 25, 0, 0, 0, TimeSpan.Zero) });
            migrationBuilder.InsertData("Faqs", new[] { "Id", "Scope", "CategoryKa", "CategoryEn", "QuestionKa", "AnswerKa", "QuestionEn", "AnswerEn", "SortOrder", "Published", "Version", "UpdatedAt" }, new object[] { new Guid("fa000000-0000-4000-8000-000000000027"), "mestia", "", "", "შემიძლია სტუმრობა სრიალის გარეშე?", "დიახ. პანორამული საბაგიროები, კვება, მთის ხედები და სეზონური აქტივობები სრიალის გარეშეც სასიამოვნო დასვენებას გთავაზობთ.", "Can I visit without skiing?", "Yes. Scenic lifts, food, mountain views and seasonal outdoor activities make the resort enjoyable beyond skiing.", 20, true, new Guid("fb000000-0000-4000-8000-000000000027"), new DateTimeOffset(2026, 9, 25, 0, 0, 0, TimeSpan.Zero) });
            migrationBuilder.InsertData("Faqs", new[] { "Id", "Scope", "CategoryKa", "CategoryEn", "QuestionKa", "AnswerKa", "QuestionEn", "AnswerEn", "SortOrder", "Published", "Version", "UpdatedAt" }, new object[] { new Guid("fa000000-0000-4000-8000-000000000028"), "mestia", "", "", "შემიძლია სკიპასის ონლაინ შეძენა?", "სკიპასის ხელმისაწვდომობის, ფასებისა და შეძენის გზების გასაგებად გამოიყენეთ სააგენტოს ოფიციალური არხები.", "Can I buy a ski pass online?", "Please use official MTA channels for current ski-pass availability, prices and purchase options.", 30, true, new Guid("fb000000-0000-4000-8000-000000000028"), new DateTimeOffset(2026, 9, 25, 0, 0, 0, TimeSpan.Zero) });
            migrationBuilder.InsertData("Faqs", new[] { "Id", "Scope", "CategoryKa", "CategoryEn", "QuestionKa", "AnswerKa", "QuestionEn", "AnswerEn", "SortOrder", "Published", "Version", "UpdatedAt" }, new object[] { new Guid("fa000000-0000-4000-8000-000000000029"), "mestia", "", "", "მუშაობს კურორტები ზაფხულში?", "ზაფხულის შეთავაზებები და სამუშაო საათები განსხვავდება. უახლესი ინფორმაციისთვის შეამოწმეთ ოფიციალური მიმდინარე სტატუსი.", "Are the resorts open during summer?", "Summer offerings and operating hours vary. Check the official live-status service for the latest information.", 40, true, new Guid("fb000000-0000-4000-8000-000000000029"), new DateTimeOffset(2026, 9, 25, 0, 0, 0, TimeSpan.Zero) });
            migrationBuilder.InsertData("Faqs", new[] { "Id", "Scope", "CategoryKa", "CategoryEn", "QuestionKa", "AnswerKa", "QuestionEn", "AnswerEn", "SortOrder", "Published", "Version", "UpdatedAt" }, new object[] { new Guid("fa000000-0000-4000-8000-000000000030"), "goderdzi", "", "", "როდის არის სტუმრობის საუკეთესო დრო?", "ზამთრისა და ზაფხულის პირობები კურორტების მიხედვით განსხვავდება. გამგზავრებამდე შეამოწმეთ ოფიციალური მიმდინარე სტატუსი.", "When is the best time to visit?", "Winter conditions and the summer mountain season differ by resort. Check the official live-status service before you travel.", 0, true, new Guid("fb000000-0000-4000-8000-000000000030"), new DateTimeOffset(2026, 9, 25, 0, 0, 0, TimeSpan.Zero) });
            migrationBuilder.InsertData("Faqs", new[] { "Id", "Scope", "CategoryKa", "CategoryEn", "QuestionKa", "AnswerKa", "QuestionEn", "AnswerEn", "SortOrder", "Published", "Version", "UpdatedAt" }, new object[] { new Guid("fa000000-0000-4000-8000-000000000031"), "goderdzi", "", "", "შეუძლიათ აქ დამწყებებს სრიალი?", "გოდერძი სხვადასხვა დონის მოთხილამურეებისთვისაა განკუთვნილი. დამწყებებმა შესაბამისი ზონები უნდა აირჩიონ და გაითვალისწინონ ინსტრუქტორის ან გიდის დახმარება.", "Can beginners ski here?", "Goderdzi offers terrain for a range of abilities. Beginners should choose suitable areas and consider a lesson or local guide.", 10, true, new Guid("fb000000-0000-4000-8000-000000000031"), new DateTimeOffset(2026, 9, 25, 0, 0, 0, TimeSpan.Zero) });
            migrationBuilder.InsertData("Faqs", new[] { "Id", "Scope", "CategoryKa", "CategoryEn", "QuestionKa", "AnswerKa", "QuestionEn", "AnswerEn", "SortOrder", "Published", "Version", "UpdatedAt" }, new object[] { new Guid("fa000000-0000-4000-8000-000000000032"), "goderdzi", "", "", "შემიძლია სტუმრობა სრიალის გარეშე?", "დიახ. პანორამული საბაგიროები, კვება, მთის ხედები და სეზონური აქტივობები სრიალის გარეშეც სასიამოვნო დასვენებას გთავაზობთ.", "Can I visit without skiing?", "Yes. Scenic lifts, food, mountain views and seasonal outdoor activities make the resort enjoyable beyond skiing.", 20, true, new Guid("fb000000-0000-4000-8000-000000000032"), new DateTimeOffset(2026, 9, 25, 0, 0, 0, TimeSpan.Zero) });
            migrationBuilder.InsertData("Faqs", new[] { "Id", "Scope", "CategoryKa", "CategoryEn", "QuestionKa", "AnswerKa", "QuestionEn", "AnswerEn", "SortOrder", "Published", "Version", "UpdatedAt" }, new object[] { new Guid("fa000000-0000-4000-8000-000000000033"), "goderdzi", "", "", "შემიძლია სკიპასის ონლაინ შეძენა?", "სკიპასის ხელმისაწვდომობის, ფასებისა და შეძენის გზების გასაგებად გამოიყენეთ სააგენტოს ოფიციალური არხები.", "Can I buy a ski pass online?", "Please use official MTA channels for current ski-pass availability, prices and purchase options.", 30, true, new Guid("fb000000-0000-4000-8000-000000000033"), new DateTimeOffset(2026, 9, 25, 0, 0, 0, TimeSpan.Zero) });
            migrationBuilder.InsertData("Faqs", new[] { "Id", "Scope", "CategoryKa", "CategoryEn", "QuestionKa", "AnswerKa", "QuestionEn", "AnswerEn", "SortOrder", "Published", "Version", "UpdatedAt" }, new object[] { new Guid("fa000000-0000-4000-8000-000000000034"), "goderdzi", "", "", "მუშაობს კურორტები ზაფხულში?", "ზაფხულის შეთავაზებები და სამუშაო საათები განსხვავდება. უახლესი ინფორმაციისთვის შეამოწმეთ ოფიციალური მიმდინარე სტატუსი.", "Are the resorts open during summer?", "Summer offerings and operating hours vary. Check the official live-status service for the latest information.", 40, true, new Guid("fb000000-0000-4000-8000-000000000034"), new DateTimeOffset(2026, 9, 25, 0, 0, 0, TimeSpan.Zero) });
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropTable(
                name: "Faqs");
        }
    }
}
