'use client';
import { useEffect, useState } from 'react';
import dynamic from 'next/dynamic';
import { Dropdown } from 'primereact/dropdown';
import { api, ApiError, type Session } from './api';
import { optionLabels, type MapFeature, type ResortMap, type MapOptions, type FeatureType, type Point } from './map-model';
const MapCanvas=dynamic(()=>import('./map-canvas'),{ssr:false,loading:()=> <p>რუკა იტვირთება / Loading canvas…</p>});
type Revision={id:number;actorName:string;at:string;action:string;beforeJson:string;afterJson:string};
function Select({label,value,values,onChange,empty=false}:{label:string;value:string;values:(string|number)[];onChange:(v:string)=>void;empty?:boolean}){
  const options=values.map(item=>({label:String(optionLabels[item]||item),value:String(item)}));
  return <label><span>{label}</span><Dropdown className="premium-dropdown" value={value} options={options} showClear={empty} placeholder={empty?'—':undefined} onChange={e=>onChange(e.value||'')}/></label>;
}
export default function MapEditor({resortId,onDirtyChange}:{resortId:string;onDirtyChange?:(dirty:boolean)=>void}){
  const [map,setMap]=useState<ResortMap|null>(null),[session,setSession]=useState<Session|null>(null),[options,setOptions]=useState<MapOptions|null>(null);
  const [draft,setDraft]=useState<MapFeature|null>(null),[drawing,setDrawing]=useState(false),[tool,setTool]=useState('select'),[vertex,setVertex]=useState<number|null>(null);
  const [error,setError]=useState(''),[notice,setNotice]=useState(''),[busy,setBusy]=useState(false),[conflict,setConflict]=useState(false),[history,setHistory]=useState<Revision[]>([]),[activity,setActivity]=useState<Revision[]>([]),[hovered,setHovered]=useState<MapFeature|null>(null),[deleteConfirm,setDeleteConfirm]=useState(false),[typeOpen,setTypeOpen]=useState(false);
  const [newType,setNewType]=useState<FeatureType>({key:'',nameKa:'',nameEn:'',geometryKind:'point',icon:'pin',color:'#17231f',statuses:['active','resolved'],active:true});
  const [pendingImage,setPendingImage]=useState<{imageUrl:string;width:number;height:number}|null>(null);
  const isAdmin=session?.role==='WebPortalAdmin';
  useEffect(()=>{let active=true;Promise.all([api<ResortMap>(`/admin/resorts/${resortId}/map`),api<Session>('/admin/session'),api<MapOptions>('/admin/map-options')]).then(async([m,s,o])=>{if(active){setMap(m);setSession(s);setOptions(o);setActivity(await api<Revision[]>(`/admin/maps/${m.id}/history`));}}).catch(e=>{if(active)setError(e.message);});return()=>{active=false;};},[resortId]);
  useEffect(()=>{if(!draft)return;const warn=(e:BeforeUnloadEvent)=>{e.preventDefault();e.returnValue='';};window.addEventListener('beforeunload',warn);return()=>window.removeEventListener('beforeunload',warn);},[draft]);
  useEffect(()=>{onDirtyChange?.(!!draft);return()=>onDirtyChange?.(false);},[draft,onDirtyChange]);
  function fail(e:unknown){setError(e instanceof Error?e.message:'შენახვა ვერ მოხერხდა / Save failed');if(e instanceof ApiError&&e.status===409)setConflict(true);}
  function start(type:FeatureType){if(draft)return;setError('');setNotice('');setTool(type.key);setDrawing(true);setVertex(null);setDraft({typeKey:type.key,geometryKind:type.geometryKind,points:[],nameKa:'',nameEn:'',descriptionKa:'',descriptionEn:'',status:type.statuses[0],difficulty:type.key==='trail'?'easy':'',liftType:type.key==='lift'?'gondola':'',opens:'',closes:'',durationMinutes:null});}
  function cancel(){setDraft(null);setDrawing(false);setTool('select');setVertex(null);setHistory([]);setDeleteConfirm(false);setError('');}
  function finish(){const minimum=draft?.geometryKind==='polygon'?3:2;if(!draft||draft.points.length<minimum){setError(`დაამატეთ მინიმუმ ${minimum} წერტილი / Add at least ${minimum} points before finishing.`);return;}setDrawing(false);setTool('select');setError('');}
  async function select(f:MapFeature){if(draft)return;setDraft(structuredClone(f));setVertex(null);setTool('select');setError('');if(f.id&&map){try{setHistory(await api<Revision[]>(`/admin/maps/${map.id}/history?featureId=${f.id}`));}catch(e){fail(e);}}}
  async function save(){if(!map||!draft||!options)return;const minimum=draft.geometryKind==='point'?1:draft.geometryKind==='polygon'?3:2;
    if(draft.points.length<minimum){setError(`საჭიროა მინიმუმ ${minimum} წერტილი / At least ${minimum} points required.`);return;}
    if(!draft.nameKa.trim()||!draft.nameEn.trim()){setError('შეავსეთ სახელი ორივე ენაზე / Enter the name in both languages.');return;}
    setBusy(true);setError('');try{const next=await api<ResortMap>(`/admin/maps/${map.id}/features${draft.id?'/'+draft.id:''}`,{method:draft.id?'PUT':'POST',body:JSON.stringify({...draft,mapVersion:map.version})});setMap(next);setActivity(await api<Revision[]>(`/admin/maps/${map.id}/history`));cancel();setNotice('შენახულია — საიტზე გამოჩნდა / Saved and live on the website.');}catch(e){fail(e);}finally{setBusy(false);}}
  async function reload(){if(!map)return;setBusy(true);try{const next=await api<ResortMap>(`/admin/resorts/${resortId}/map`);setMap(next);setActivity(await api<Revision[]>(`/admin/maps/${next.id}/history`));cancel();setConflict(false);setNotice('რუკა განახლებულია / Latest map loaded.');}catch(e){fail(e);}finally{setBusy(false);}}
  async function remove(){if(!map||!draft?.id)return;setBusy(true);try{setMap(await api<ResortMap>(`/admin/maps/${map.id}/features/${draft.id}?mapVersion=${map.version}&version=${draft.version}`,{method:'DELETE'}));setActivity(await api<Revision[]>(`/admin/maps/${map.id}/history`));cancel();setNotice('წაშლილია / Deleted. History retained.');}catch(e){fail(e);}finally{setBusy(false);}}
  async function upload(file:File|undefined){if(!file)return;setBusy(true);try{const body=new FormData();body.set('file',file);setPendingImage(await api('/admin/map-image',{method:'POST',body}));}catch(e){fail(e);}finally{setBusy(false);}}
  async function replaceImage(){if(!map||!pendingImage)return;setBusy(true);try{setMap(await api(`/admin/maps/${map.id}/image`,{method:'PUT',body:JSON.stringify({...pendingImage,version:map.version})}));setPendingImage(null);setNotice('რუკის ფოტო შენახულია / Base map saved.');}catch(e){fail(e);}finally{setBusy(false);}}
  async function createType(){setBusy(true);try{await api('/admin/map-types',{method:'POST',body:JSON.stringify(newType)});await reload();setTypeOpen(false);}catch(e){fail(e);}finally{setBusy(false);}}
  function set<K extends keyof MapFeature>(key:K,value:MapFeature[K]){setDraft(d=>d?{...d,[key]:value}:null);}
  if(!map||!options)return <section className="map-editor"><h3>რუკის რედაქტორი / Map editor</h3><p role={error?'alert':'status'}>{error||'იტვირთება / Loading…'}</p></section>;
  const draftType=map.types.find(t=>t.key===draft?.typeKey);
  return <section className="map-editor" aria-label="Visual map editor"><header><h3>რუკის რედაქტორი / Visual map editor</h3><p>დახატეთ რუკაზე, შეავსეთ ინფორმაცია და შეინახეთ. / Draw on the map, add details, save to the site.</p></header>
    {error&&<p className="map-error" role="alert">{error}</p>}{notice&&<p role="status">{notice}</p>}
    {conflict&&<div className="map-error"><p>თქვენი ნახაზი შენარჩუნებულია. განახლება გააუქმებს შეუნახავ ცვლილებებს. / Your drawing is still visible. Reload discards unsaved changes.</p><button type="button" disabled={busy} onClick={reload}>განახლება და ცვლილებების გაუქმება / Reload and discard</button></div>}
    {map.placeholder&&<p className="map-note">საჩვენებელი ფონი — ატვირთეთ კურორტის ოფიციალური რუკა. / Placeholder background. Upload the resort’s official map before drawing operational routes.</p>}
    <fieldset disabled={busy||conflict} className="map-controls"><legend className="sr-only">სახატავი ხელსაწყოები / Drawing tools</legend><div className="map-toolbar" role="toolbar" aria-label="Drawing tools">
      <button type="button" aria-pressed={tool==='select'} onClick={()=>setTool('select')}>↖ არჩევა / Select</button>
      {map.types.filter(t=>t.active).sort((a,b)=>['trail','lift','warning'].indexOf(a.key)-['trail','lift','warning'].indexOf(b.key)).map(type=><button key={type.key} type="button" disabled={!!draft} aria-pressed={tool===type.key} onClick={()=>start(type)}><span style={{color:type.color}}>{type.icon==='warning'?'⚠':type.icon==='lift'?'┃':'●'}</span> {type.nameKa} / {type.nameEn}</button>)}
      <button type="button" aria-pressed={tool==='pan'} onClick={()=>setTool(tool==='pan'?'select':'pan')}>✋ გადაადგილება / Pan</button>
      {drawing&&<><button type="button" onClick={finish}>დასრულება / Finish</button><button type="button" disabled={!draft?.points.length} onClick={()=>set('points',draft!.points.slice(0,-1))}>უკან / Undo point</button></>}
      {draft&&<button type="button" onClick={cancel}>გაუქმება / Cancel</button>}
    </div></fieldset>
    <div className="map-editor-grid"><div style={{pointerEvents:busy||conflict?'none':undefined}}>
      <MapCanvas map={map} draft={draft} drawing={drawing} pan={tool==='pan'} selectedVertex={vertex}
        onPoint={p=>{setDraft(current=>current?{...current,points:[...current.points,p]}:null);if(draft?.geometryKind==='point'){setDrawing(false);setTool('select');}}}
        onSelect={select} onVertex={(i,p)=>setDraft(current=>current?{...current,points:current.points.map((v,j)=>i===j?p:v)}:null)} onVertexSelect={setVertex}
        onHandle={(i,side,p)=>setDraft(current=>{if(!current)return null;const points=current.points.map((anchor,j)=>{if(i!==j)return anchor;const next=[...anchor] as Point;if(side==='in'){next[2]=p[0];next[3]=p[1];if(anchor.length<6){next[4]=anchor[0]*2-p[0];next[5]=anchor[1]*2-p[1];}}else{next[4]=p[0];next[5]=p[1];if(anchor.length<6){next[2]=anchor[0]*2-p[0];next[3]=anchor[1]*2-p[1];}}return next;});return {...current,points};})}
        onInsert={(i,p)=>{setDraft(current=>current?{...current,points:[...current.points.slice(0,i),p,...current.points.slice(i)]}:null);setVertex(i);}}
        onHover={setHovered} />
      {hovered&&!draft&&<div className="map-hover-audit"><strong>{hovered.nameKa} / {hovered.nameEn}</strong><span>შექმნა / Created: {hovered.createdByName||'—'} · {hovered.createdAt?new Date(hovered.createdAt).toLocaleString():'—'}</span><span>ბოლო ცვლილება / Last edit: {hovered.updatedByName||'—'} · {hovered.updatedAt?new Date(hovered.updatedAt).toLocaleString():'—'}</span></div>}
      {draft&&!drawing&&<div className="map-toolbar"><span>{draft.points.length} წერტილი / points</span><button type="button" disabled={vertex===null||draft.geometryKind==='point'||busy||conflict} onClick={()=>{const min=draft.geometryKind==='polygon'?3:2;if(draft.points.length<=min){setError(`მინიმუმ ${min} წერტილი უნდა დარჩეს / Keep at least ${min} points.`);return;}set('points',draft.points.filter((_,i)=>i!==vertex));setVertex(null);}}>არჩეული წერტილის წაშლა / Delete selected vertex</button></div>}
      <details><summary>ობიექტების სია / Features ({map.features.length})</summary><div className="map-feature-list">{map.features.map(f=><button type="button" key={f.id} disabled={!!draft} onClick={()=>select(f)}>{f.nameKa} / {f.nameEn}</button>)}</div></details>
    </div>
    {draft&&!drawing?<form className="map-metadata" onSubmit={e=>{e.preventDefault();void save();}}><fieldset disabled={busy||conflict}><legend>{draftType?.nameKa} / {draftType?.nameEn}</legend>
      {(['ka','en'] as const).map(locale=><div className="stack" key={locale}><h4>{locale==='ka'?'ქართული':'English'}</h4><label>{locale==='ka'?'სახელი':'Name'}<input required maxLength={200} value={locale==='ka'?draft.nameKa:draft.nameEn} onChange={e=>set(locale==='ka'?'nameKa':'nameEn',e.target.value)}/></label><label>{locale==='ka'?'აღწერა':'Description'}<textarea rows={3} maxLength={5000} value={locale==='ka'?draft.descriptionKa:draft.descriptionEn} onChange={e=>set(locale==='ka'?'descriptionKa':'descriptionEn',e.target.value)}/></label></div>)}
      <Select label="სტატუსი / Status" value={draft.status} values={draftType?.statuses||[]} onChange={v=>set('status',v)}/>
      {draft.typeKey==='trail'&&<Select label="სირთულე / Difficulty" value={draft.difficulty} values={options.difficulties} onChange={v=>set('difficulty',v)}/>}
      {draft.typeKey==='lift'&&<><Select label="საბაგიროს ტიპი / Lift type" value={draft.liftType} values={options.liftTypes} onChange={v=>set('liftType',v)}/><Select empty label="გახსნა / Opens" value={draft.opens} values={options.times} onChange={v=>set('opens',v)}/><Select empty label="დახურვა / Closes" value={draft.closes} values={options.times} onChange={v=>set('closes',v)}/><Select empty label="მგზავრობა (წთ) / Ride duration (min)" value={draft.durationMinutes===null?'':String(draft.durationMinutes)} values={options.durations} onChange={v=>set('durationMinutes',v?Number(v):null)}/></>}
      {draft.createdAt&&<div className="map-audit"><p>შექმნა / Created: {draft.createdByName} — {new Date(draft.createdAt).toLocaleString()}</p><p>განახლება / Edited: {draft.updatedByName} — {new Date(draft.updatedAt!).toLocaleString()}</p></div>}
      <div className="map-toolbar"><button type="submit">შენახვა / Save — live</button><button type="button" onClick={cancel}>გაუქმება / Cancel</button>{isAdmin&&draft.id&&<button type="button" onClick={()=>setDeleteConfirm(true)}>წაშლა / Delete</button>}</div>
      {deleteConfirm&&<div role="alert"><p>წაიშალოს საიტიდან? ისტორია შენარჩუნდება. / Remove from the website? History is retained.</p><button type="button" onClick={remove}>დიახ, წაშლა / Confirm delete</button><button type="button" onClick={()=>setDeleteConfirm(false)}>გაუქმება / Cancel</button></div>}
    </fieldset><History rows={history}/></form>:<aside className="map-metadata"><h4>{drawing?'დახატეთ / Draw':'აირჩიეთ ხელსაწყო / Select a tool'}</h4><p>{drawing?'შეეხეთ რუკას წერტილების დასამატებლად, შემდეგ დააჭირეთ დასრულებას. / Click or tap points on the map, then Finish.':'აირჩიეთ ტრასა, საბაგირო ან გაფრთხილება. არსებული ობიექტის შესაცვლელად დააჭირეთ მას. / Choose Trail, Lift or Warning, or select an existing feature.'}</p></aside>}
    </div>
    <section className="map-activity"><div><span className="eyebrow">Audit trail</span><h4>ბოლო აქტივობა / Recent map activity</h4></div><History rows={activity} open/></section>
    <div className="map-toolbar">{isAdmin&&<button type="button" disabled={!!draft} onClick={()=>setTypeOpen(!typeOpen)}>ტიპის დამატება / Add feature type</button>}</div>
    {isAdmin&&<details><summary>რუკის ფონის შეცვლა / Replace base map</summary><p>Reference: {map.width} × {map.height}px. გადაამოწმეთ ყველა ობიექტის მდებარეობა. / Check alignment of every feature when changing artwork.</p><input type="file" accept="image/png,image/jpeg,image/webp" disabled={busy||!!draft} aria-label="Upload map image" onChange={e=>{void upload(e.target.files?.[0]);e.target.value='';}}/>{pendingImage&&<><img className="map-image-preview" src={pendingImage.imageUrl} alt="New base map preview"/><p>{pendingImage.width} × {pendingImage.height}px</p><button type="button" disabled={busy} onClick={replaceImage}>ფონის შენახვა / Save base map</button><button type="button" onClick={()=>setPendingImage(null)}>გაუქმება / Cancel</button></>}</details>}
    {typeOpen&&<fieldset className="map-metadata"><legend>ახალი ტიპი / New feature type</legend>{(['key','nameKa','nameEn'] as const).map(k=><label key={k}>{k}<input maxLength={120} value={newType[k]} onChange={e=>setNewType({...newType,[k]:e.target.value})}/></label>)}<Select label="Shape" value={newType.geometryKind} values={['point','line','polygon']} onChange={v=>setNewType({...newType,geometryKind:v as FeatureType['geometryKind']})}/><Select label="Icon" value={newType.icon} values={['pin','trail','lift','warning']} onChange={v=>setNewType({...newType,icon:v})}/><label>Color<input type="color" value={newType.color} onChange={e=>setNewType({...newType,color:e.target.value})}/></label><button type="button" disabled={busy} onClick={createType}>შენახვა / Save type</button></fieldset>}
  </section>;
}
function History({rows,open=false}:{rows:Revision[];open?:boolean}){return <details open={open}><summary>ისტორია / History ({rows.length})</summary>{rows.length===0?<p className="muted">აქტივობა ჯერ არ არის / No activity yet.</p>:rows.slice(0,20).map(r=>{let name='';try{const after=JSON.parse(r.afterJson||'null'),before=JSON.parse(r.beforeJson||'null');name=after?.nameKa||after?.NameKa||before?.nameKa||before?.NameKa||'';}catch{}return <article className="map-audit" key={r.id}><div><strong>{name||'Map feature'}</strong><span>{r.actorName} · {r.action} · {new Date(r.at).toLocaleString()}</span></div><details><summary>ცვლილებები / Changes</summary><pre>{JSON.stringify({before:JSON.parse(r.beforeJson||'null'),after:JSON.parse(r.afterJson||'null')},null,2)}</pre></details></article>;})}</details>;}
