'use client';
import { useCallback, useEffect, useId, useState } from 'react';
import { useRouter } from 'next/navigation';
import Link from 'next/link';
import { Button } from 'primereact/button';
import { Dropdown } from 'primereact/dropdown';
import { InputText } from 'primereact/inputtext';
import { InputTextarea } from 'primereact/inputtextarea';
import { Message } from 'primereact/message';
import { Dialog } from 'primereact/dialog';
import { api, type Session } from './api';
import { BrandLogo } from './brand';
import MapEditor from './map-editor';
import ResortPageEditor from './resort-page-editor';
import { HoursSelect, SeasonSelect } from './time-controls';
import { blankResort, conditionLabels, infoFields, preview, statusOptions, type Conditions, type LiveCardSettings, type Resort, type ResortContent } from './resort-model';

const sections = [
  ['general','pi pi-home','General'],['media','pi pi-images','Hero & media'],['stats','pi pi-chart-bar','Key stats'],['content','pi pi-align-left','Content'],
  ['infrastructure','pi pi-list','Lifts & trails'],['activities','pi pi-sparkles','Activities'],['travel','pi pi-car','Travel'],['map','pi pi-map','Interactive map'],['publishing','pi pi-share-alt','PDF & social'],
] as const;
type FieldErrors = Partial<Record<'slug'|'kaName'|'enName'|'kaRegion'|'enRegion'|'kaDescription'|'enDescription'|'image'|'summerImage',string>>;

export default function ResortEditorScreen({ resortId }: { resortId?: string }) {
  const router = useRouter();
  const [initial,setInitial]=useState<Resort|null>(null),[session,setSession]=useState<Session|null>(null),[loading,setLoading]=useState(true),[loadError,setLoadError]=useState('');
  useEffect(()=>{let active=true;Promise.all([api<Session>('/admin/session'),resortId?api<Resort[]>('/admin/resorts'):Promise.resolve([])]).then(([s,rows])=>{if(!active)return;setSession(s);if(!s.authenticated){router.replace('/?section=resorts');return;}const item=resortId?rows.find(r=>r.id===resortId):blankResort();if(!item)setLoadError('კურორტი ვერ მოიძებნა / Resort not found.');else setInitial(item);}).catch(e=>{if(active)setLoadError(e instanceof Error?e.message:'გვერდი ვერ ჩაიტვირთა.');}).finally(()=>{if(active)setLoading(false);});return()=>{active=false;};},[resortId,router]);
  if(loading)return <main className="editor-page-state" role="status"><BrandLogo priority/><i className="pi pi-spin pi-spinner"/><p>კურორტის სამუშაო სივრცე იტვირთება…</p></main>;
  if(loadError||!initial||!session?.authenticated)return <main className="editor-page-state"><BrandLogo priority/><Message severity="error" text={loadError||'გაიარეთ ავტორიზაცია / Please sign in.'}/><Link href="/?section=resorts">← კურორტების სიაზე დაბრუნება</Link></main>;
  return <ResortWorkspace key={initial.id||'new'} initial={initial} onReplace={next=>{setInitial(next);if(!resortId)router.replace(`/resorts/${next.id}/edit`);}} onBack={()=>router.push('/?section=resorts')}/>;
}

function ResortWorkspace({initial,onReplace,onBack}:{initial:Resort;onReplace:(next:Resort)=>void;onBack:()=>void}){
  const [draft,setDraft]=useState(()=>structuredClone(initial)),[locale,setLocale]=useState<'ka'|'en'>('ka'),[busy,setBusy]=useState(false),[uploading,setUploading]=useState(false);
  const [error,setError]=useState(''),[notice,setNotice]=useState(''),[discard,setDiscard]=useState(false),[fieldErrors,setFieldErrors]=useState<FieldErrors>({}),[mapDirty,setMapDirty]=useState(false);
  const fileId=useId(),data=draft[locale],recordDirty=JSON.stringify(draft)!==JSON.stringify(initial),dirty=recordDirty||mapDirty;
  useEffect(()=>{if(!dirty)return;const warn=(e:BeforeUnloadEvent)=>{e.preventDefault();e.returnValue='';};window.addEventListener('beforeunload',warn);return()=>window.removeEventListener('beforeunload',warn);},[dirty]);
  function setField<K extends keyof ResortContent>(key:K,value:ResortContent[K]){setDraft(d=>({...d,[locale]:{...d[locale],[key]:value}}));setFieldErrors({});setNotice('');}
  function validate(){const next:FieldErrors={};if(!draft.slug.trim())next.slug='Slug is required.';if(!/^[a-z0-9]+(?:-[a-z0-9]+)*$/.test(draft.slug))next.slug='Use lowercase Latin letters, numbers and hyphens.';for(const lang of ['ka','en'] as const){const prefix=lang==='ka'?'ka':'en';if(!draft[lang].name.trim())next[`${prefix}Name`]='Required / სავალდებულოა';if(!draft[lang].region.trim())next[`${prefix}Region`]='Required / სავალდებულოა';if(!draft[lang].description.trim())next[`${prefix}Description`]='Required / სავალდებულოა';}if(!draft.ka.image||!draft.en.image)next.image='Upload a winter cover.';if(!draft.ka.summerImage||!draft.en.summerImage)next.summerImage='Upload a summer cover.';setFieldErrors(next);return Object.keys(next).length===0;}
  async function save(){if(!validate()){setError('გადაამოწმეთ მონიშნული ველები / Review the highlighted fields.');document.querySelector('.is-invalid')?.scrollIntoView({behavior:'smooth',block:'center'});return;}setBusy(true);setError('');setNotice('');try{const saved=await api<Resort>(initial.id?`/admin/resorts/${initial.id}`:'/admin/resorts',{method:initial.id?'PUT':'POST',body:JSON.stringify({...draft,version:draft.version||null})});setDraft(structuredClone(saved));onReplace(saved);setNotice('ცვლილებები შენახულია და საიტზე განახლდა / Saved and published.');}catch(e){setError(e instanceof Error?e.message:'შენახვა ვერ მოხერხდა.');}finally{setBusy(false);}}
  async function upload(file:File|undefined,season:'winter'|'summer'){if(!file)return;if(file.size>5*1024*1024){setError('ფოტოს მაქსიმალური ზომაა 5 MB.');return;}setUploading(true);setError('');try{const body=new FormData();body.set('file',file);const {url}=await api<{url:string}>('/admin/media',{method:'POST',body});setDraft(d=>{const next=structuredClone(d);for(const lang of ['ka','en'] as const){const c=next[lang];if(season==='winter'){c.image=url;c.heroImages=[url];if(!c.summerImage)c.summerImage=url;}else{c.summerImage=url;if(!c.image){c.image=url;c.heroImages=[url];}}c.seasons={winter:{image:c.image,heroImages:c.heroImages.length?c.heroImages:[c.image]},summer:{image:c.summerImage,heroImages:season==='summer'?[url]:(c.seasons?.summer.heroImages||[c.summerImage])}};}return next;});setFieldErrors({});}catch(e){setError(e instanceof Error?e.message:'ატვირთვა ვერ მოხერხდა.');}finally{setUploading(false);}}
  const invalid=(key:keyof FieldErrors)=>fieldErrors[key]?'is-invalid':'';
  return <main className="resort-editor-page">
    <header className="resort-editor-sticky"><div className="resort-editor-title"><button type="button" className="back-link" onClick={()=>dirty?setDiscard(true):onBack()}><i className="pi pi-arrow-left"/> Back to Resorts</button><div><span className="eyebrow">RESORT WORKSPACE</span><h1>{initial.id?(draft.ka.name||'კურორტის რედაქტირება'):'ახალი კურორტი / New resort'}</h1></div></div><div className="save-cluster"><span className={`save-state ${dirty?'dirty':'saved'}`}><i className={dirty?'pi pi-circle-fill':'pi pi-check-circle'}/>{mapDirty&&!recordDirty?'დაასრულეთ რუკის ობიექტი / Finish map feature':dirty?'შეუნახავი ცვლილებები / Unsaved':'ყველაფერი შენახულია / Saved'}</span><Button label="შენახვა / Save" icon="pi pi-check" loading={busy} disabled={uploading||!recordDirty} onClick={()=>void save()}/></div></header>
    <div className="resort-editor-body"><aside className="resort-section-nav" aria-label="Editor sections"><BrandLogo/>{sections.map(([id,icon,label],index)=><a key={id} href={`#${id}`}><i className={icon}/><span>{String(index+1).padStart(2,'0')}</span>{label}</a>)}</aside>
      <div className="resort-editor-content">
        <div className="editor-language-bar"><div><strong>Content language</strong><small>Switch language without losing changes.</small></div><div className="language-tabs"><button type="button" className={locale==='ka'?'selected':''} aria-pressed={locale==='ka'} onClick={()=>setLocale('ka')}>ქართული <span>KA</span></button><button type="button" className={locale==='en'?'selected':''} aria-pressed={locale==='en'} onClick={()=>setLocale('en')}>English <span>EN</span></button></div></div>
        {error&&<div className="editor-banner error" role="alert"><i className="pi pi-exclamation-circle"/><span>{error}</span><button onClick={()=>setError('')} aria-label="Close">×</button></div>}{notice&&<div className="editor-banner success" role="status"><i className="pi pi-check-circle"/><span>{notice}</span><button onClick={()=>setNotice('')} aria-label="Close">×</button></div>}
        <EditorCard id="general" step="01" title="General information" note="Identity, bilingual names and publishing status."><div className="premium-grid two"><Field label={locale==='ka'?'კურორტის სახელი':'Resort name'} error={fieldErrors[locale==='ka'?'kaName':'enName']}><InputText className={invalid(locale==='ka'?'kaName':'enName')} value={data.name} maxLength={200} onChange={e=>setField('name',e.target.value)}/></Field><Field label={locale==='ka'?'რეგიონი':'Region'} error={fieldErrors[locale==='ka'?'kaRegion':'enRegion']}><InputText className={invalid(locale==='ka'?'kaRegion':'enRegion')} value={data.region} maxLength={200} onChange={e=>setField('region',e.target.value)}/></Field></div><Field label={locale==='ka'?'მოკლე აღწერა':'Short description'} error={fieldErrors[locale==='ka'?'kaDescription':'enDescription']}><InputTextarea className={invalid(locale==='ka'?'kaDescription':'enDescription')} rows={5} maxLength={20000} value={data.description} onChange={e=>setField('description',e.target.value)}/></Field><div className="premium-grid two"><Field label="URL slug" error={fieldErrors.slug} hint="Lowercase Latin letters, numbers and hyphens."><InputText className={invalid('slug')} disabled={!!initial.id} value={draft.slug} maxLength={150} onChange={e=>setDraft({...draft,slug:e.target.value.toLowerCase()})}/></Field><Field label="Status"><Dropdown className="premium-dropdown" disabled={draft.liveManaged} options={statusOptions} value={draft.status} onChange={e=>setDraft({...draft,status:e.value})}/></Field></div></EditorCard>
        <EditorCard id="media" step="02" title="Hero & media" note="Seasonal covers, homepage card artwork and a shared 12-image gallery."><div className="media-grid">{(['winter','summer'] as const).map(season=>{const path=season==='winter'?data.image:data.summerImage,key=season==='winter'?'image':'summerImage';return <div className={`media-upload ${invalid(key)}`} key={season}><div className="media-preview">{path?<img src={preview(path)} alt=""/>:<div><i className="pi pi-image"/><span>No image uploaded</span></div>}</div><div><strong>{season==='winter'?'Winter cover':'Summer cover'}</strong><small>JPG, PNG or WebP · max 5 MB</small><label className="upload-button" htmlFor={fileId+season}><i className="pi pi-upload"/> Replace image</label><input className="file-input" id={fileId+season} type="file" accept="image/jpeg,image/png,image/webp" disabled={busy||uploading} onChange={e=>{void upload(e.target.files?.[0],season);e.target.value='';}}/>{fieldErrors[key]&&<em>{fieldErrors[key]}</em>}</div></div>;})}</div><ResortGalleryEditor images={data.gallery} disabled={busy||uploading} onBusy={setUploading} onChange={gallery=>setDraft(current=>({...current,ka:{...current.ka,gallery},en:{...current.en,gallery}}))}/><LiveCardEditor resort={draft} locale={locale} disabled={busy||uploading} onBusy={setUploading} onChange={(settings,shared)=>setDraft(d=>{const next=structuredClone(d);for(const lang of shared?['ka','en'] as const:[locale])next[lang].liveCard={...next[lang].liveCard,...settings};return next;})}/></EditorCard>
        <EditorCard id="stats" step="03" title="Key stats" note="Operational values and season information."><div className="premium-grid three">{infoFields.map(([key,label])=><Field key={key} label={label}>{key==='hours'?<HoursSelect disabled={draft.liveManaged} value={data.hours} onChange={v=>setField('hours',v)}/>:key==='winterSeason'?<SeasonSelect locale={locale} value={data.winterSeason} onChange={v=>setField('winterSeason',v)}/>:<InputText readOnly={draft.liveManaged&&['lifts','trails','temp','snow','newSnow','wind'].includes(key)} maxLength={200} value={data[key]} onChange={e=>setField(key,e.target.value)}/>}</Field>)}</div></EditorCard>
        <ResortPageEditor value={data.page} lifts={data.liftList} activities={data.experience.winter} locale={locale} disabled={busy||uploading} onBusy={setUploading} onChange={page=>setField('page',page)} transport={data.transport} onTransportChange={transport=>setField('transport',transport)} mapSlot={initial.id?<EditorCard id="map" step="08" title="Interactive map" note="Draw live trails, lifts and warnings directly over the reference map."><MapEditor resortId={initial.id} onDirtyChange={setMapDirty}/></EditorCard>:<EditorCard id="map" step="08" title="Interactive map" note="Save the resort once to create its map workspace."><div className="premium-empty"><i className="pi pi-map"/><h3>Map workspace unlocks after first save</h3><p>Complete the required general fields and covers, then save this resort.</p></div></EditorCard>}/>
      </div>
    </div>
    <Dialog visible={discard} onHide={()=>setDiscard(false)} header="შეუნახავი ცვლილებები / Unsaved changes" modal style={{width:'460px',maxWidth:'95vw'}} footer={<><Button text label="გაგრძელება / Keep editing" onClick={()=>setDiscard(false)}/><Button severity="danger" label="გასვლა / Discard" onClick={onBack}/></>}><p>გასვლის შემთხვევაში შეუნახავი ცვლილებები დაიკარგება.</p></Dialog>
  </main>;
}

function EditorCard({id,step,title,note,children}:{id:string;step:string;title:string;note:string;children:React.ReactNode}){return <section id={id} className="premium-card"><header><span>{step}</span><div><h2>{title}</h2><p>{note}</p></div></header><div className="premium-card-body">{children}</div></section>;}
function Field({label,hint,error,children}:{label:string;hint?:string;error?:string;children:React.ReactNode}){return <label className={error?'field-invalid':''}><span>{label}</span>{children}{hint&&<small>{hint}</small>}{error&&<em role="alert">{error}</em>}</label>;}

function LiveCardEditor({resort,locale,disabled,onBusy,onChange}:{resort:Resort;locale:'ka'|'en';disabled:boolean;onBusy:(busy:boolean)=>void;onChange:(settings:Partial<LiveCardSettings>,shared:boolean)=>void}){
  const settings=resort[locale].liveCard||{},id=useId();const [error,setError]=useState(''),[conditions,setConditions]=useState<Conditions|null>(null);
  const loadConditions=useCallback(()=>api<Conditions[]>('/resorts/conditions').then(rows=>setConditions(rows.find(row=>row.resortId===resort.id)||null)).catch(()=>setConditions(null)),[resort.id]);
  useEffect(()=>{void loadConditions();},[loadConditions]);
  async function uploadCard(file:File|undefined,season:'winter'|'summer'){if(!file)return;if(file.size>5*1024*1024){setError('Maximum 5 MB');return;}setError('');onBusy(true);try{const body=new FormData();body.set('file',file);const {url}=await api<{url:string}>('/admin/media',{method:'POST',body});onChange({[season==='winter'?'winterImage':'summerImage']:url},true);}catch(e){setError(e instanceof Error?e.message:'Upload failed');}finally{onBusy(false);}}
  return <div className="live-card-premium"><div className="subsection-heading"><div><h3>Homepage live card</h3><p>Shared display settings and season-specific card art.</p></div><span>LIVE CARD</span></div>{error&&<p role="alert" className="inline-error">{error}</p>}<fieldset disabled={disabled}><div className="premium-grid two">{(['winter','summer'] as const).map(season=>{const key=season==='winter'?'winterImage':'summerImage',path=settings[key]||(season==='winter'?resort[locale].image:resort[locale].summerImage);return <div className="mini-media" key={season}>{path?<img src={preview(path)} alt=""/>:<i className="pi pi-image"/>}<div><strong>{season==='winter'?'Winter card':'Summer card'}</strong><input aria-label={`${season} card image`} type="file" accept="image/jpeg,image/png,image/webp" onChange={e=>{void uploadCard(e.target.files?.[0],season);e.target.value='';}}/></div></div>;})}</div><div className="premium-grid two"><Field label={`Image alt · ${locale.toUpperCase()}`}><InputText id={id+'alt'} value={settings.imageAlt||''} maxLength={400} onChange={e=>onChange({imageAlt:e.target.value},false)}/></Field><Field label={`Card note · ${locale.toUpperCase()}`}><InputTextarea id={id+'note'} rows={3} value={settings.note||''} maxLength={400} onChange={e=>onChange({note:e.target.value},false)}/></Field></div><div className="toggle-row"><label><input type="checkbox" checked={settings.featured===true} onChange={e=>onChange({featured:e.target.checked},true)}/> Featured</label><label><input type="checkbox" checked={settings.homepageVisible!==false} onChange={e=>onChange({homepageVisible:e.target.checked},true)}/> Show on homepage</label><Field label="Display order"><InputText type="number" min={0} max={999} value={String(settings.displayOrder??100)} onChange={e=>onChange({displayOrder:Math.min(999,Math.max(0,Number(e.target.value)||0))},true)}/></Field></div></fieldset>{resort.id&&<details className="live-observations"><summary>Current live observations</summary><dl>{(Object.keys(conditionLabels) as (keyof typeof conditionLabels)[]).map(key=><div key={key}><dt>{conditionLabels[key]}</dt><dd>{conditions?.[key]??'—'}</dd></div>)}</dl></details>}</div>;
}

function ResortGalleryEditor({images,disabled,onBusy,onChange}:{images:string[];disabled:boolean;onBusy:(busy:boolean)=>void;onChange:(images:string[])=>void}){
  const id=useId();const [error,setError]=useState('');
  async function upload(files:FileList|null){if(!files?.length)return;const selected=Array.from(files).slice(0,12-images.length);if(selected.some(file=>file.size>5*1024*1024)){setError('Each image must be 5 MB or smaller.');return;}onBusy(true);setError('');try{const uploaded=[];for(const file of selected){const body=new FormData();body.set('file',file);uploaded.push((await api<{url:string}>('/admin/media',{method:'POST',body})).url);}onChange([...images,...uploaded].slice(0,12));}catch(e){setError(e instanceof Error?e.message:'Gallery upload failed.');}finally{onBusy(false);}}
  function move(index:number,direction:-1|1){const target=index+direction;if(target<0||target>=images.length)return;const next=[...images];[next[index],next[target]]=[next[target],next[index]];onChange(next);}
  return <div className="resort-gallery-admin"><div className="subsection-heading"><div><h3>Photo gallery</h3><p>Shared by both languages · up to 12 images · drag-free accessible ordering.</p></div><span>{images.length}/12</span></div>{error&&<p className="inline-error" role="alert">{error}</p>} {!images.length&&<div className="premium-empty compact"><i className="pi pi-images"/><h3>No gallery images yet</h3><p>Upload photographs to build the resort mosaic.</p></div>}<div className="resort-gallery-admin__grid">{images.map((image,index)=><article key={`${image}:${index}`}><img src={preview(image)} alt={`Gallery ${index+1}`}/><div><button type="button" disabled={disabled||index===0} onClick={()=>move(index,-1)} aria-label={`Move image ${index+1} left`}><i className="pi pi-arrow-left"/></button><span>{index+1}</span><button type="button" disabled={disabled||index===images.length-1} onClick={()=>move(index,1)} aria-label={`Move image ${index+1} right`}><i className="pi pi-arrow-right"/></button><button type="button" disabled={disabled} onClick={()=>onChange(images.filter((_,item)=>item!==index))} aria-label={`Delete image ${index+1}`}><i className="pi pi-trash"/></button></div></article>)}</div>{images.length<12&&<><label className="upload-button" htmlFor={id}><i className="pi pi-plus"/> Upload gallery images</label><input id={id} className="file-input" multiple type="file" accept="image/jpeg,image/png,image/webp" disabled={disabled} onChange={event=>{void upload(event.target.files);event.target.value='';}}/></>}</div>;
}
